# Используем образ Maven для сборки
FROM maven:3.8.4-openjdk-17 AS builder
WORKDIR /app
# Копируем файлы проекта
COPY . /app/
# Собираем проект, пропуская тесты
RUN mvn clean package -Dmaven.test.skip=true

# Используем образ OpenJDK для выполнения приложения
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
# Копируем собранный jar файл из предыдущего этапа
COPY --from=builder /app/target/*.jar /app/app.jar
# Открываем порт 8181
EXPOSE 8181
# Указываем команду для запуска приложения
ENTRYPOINT ["java", "-jar", "/app/app.jar"]